name: Build Overlay
on: [push]
jobs:
  Build-Overlay-Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: python -m pip install twitchAPI==4.2.0 pyinstaller==6.8.0 pygame==2.4.0
      - name: Package overlay application
        run: |
          pyinstaller zingo-fight-pit.py
          copy "./dist/zingo-fight-pit/zingo-fight-pit.exe" "./zingo-fight-pit.exe"
          copy "./settings_template.json" "./settings.json"
          robocopy "./dist/zingo-fight-pit/_internal" "_internal" /e
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zingo-fight-pit-win
          path: |
            zingo-fight-pit.exe
            _internal
            skins/*
            bubble.png
            settings.json
      
